# Generated by Django 2.2 on 2019-05-23 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('effervesence', 'efferversence'), ('studies', 'studies')], max_length=30)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('roll_no', models.CharField(max_length=20)),
                ('dislike', models.ManyToManyField(blank=True, related_name='disliked', to='doubt.Question')),
                ('liked', models.ManyToManyField(blank=True, related_name='liked_ques', to='doubt.Question')),
                ('my_question', models.ManyToManyField(blank=True, related_name='asked_question', to='doubt.Question')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
                ('visited', models.ManyToManyField(blank=True, related_name='visited_ques', to='doubt.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('anonymous', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='reply',
            field=models.ManyToManyField(to='doubt.Reply'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='visited',
            field=models.ManyToManyField(blank=True, related_name='visited_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
