# Generated by Django 2.2 on 2019-05-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='reply',
            field=models.ManyToManyField(blank=True, to='doubt.Reply'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roll_no',
            field=models.CharField(default='', max_length=20),
        ),
    ]
